### PR TITLE
Added curl for fetching badges and header for github authorization

### PR DESCRIPTION
**Pull request by bogdanRada**
Also i added posibility to log all curl requests to a log file so that will be easier to debug next time something happens..

For github authorization to work, you must go into your profile here: https://github.com/settings/tokens and create a token, then go to Heroku.com, to your application in Settings tab under Config variables , add new config variable with name GITHUB_API_KEY and put the token generated previously to the value attribute

Then you can deploy this and everything wil work

The reason why this is needed is because you're doing unauthenticated requests, which now has a limit of 60 requests allowed per hour, but this is used in 75 repositories at the moment.   

Doing authenticated requests, will allow you to do 5000 requests per hour, and this will solve this problem with badges. 

Please let me know what you think . Thank you very much.

### CODE REVIEW

**Comment by ruddfawcett** [comment]
Thanks, I'll take a look!

**Comment by ruddfawcett** [comment]
I'm currently working on another project, so I don't really have time to pursue this further.  However, if you can get this working on another Heroku server, I'd be more than happy to merge any further changes.  Thasnk! :smile:

**Comment by bogdanRada** [comment]
I fixed the problem. Forgot that getenv is a function not a array.

Here is a demo: 

``` ruby
  ![](https://reposs-badge.herokuapp.com/?path=rails/rails)
```

**Comment by ruddfawcett** [comment]
Thanks for your work on this! ⭐️

**Comment by bogdanRada** [comment]
my pleasure :)

**Comment by thatsIch** [comment]
Thank you!

**Pull request merged**
